instanceID: "sean-apigee-instance"
namespace: "apigee"
projectId: "apigee-hybrid-terraform-test"
analyticsRegion: "us-central1"
gsa: "SA"
clusterName: "cluster-1"
clusterLocation: "us-central1"
orgName: "apigee-hybrid-terraform-test"
envGroupName: "hybrid"
sslCertPath: "certs/keystore_hybrid.pem"
sslKeyPath: "certs/keystore_hybrid.key"
ingressName: "apigee-hybrid-ing"
envName: "hybrid-env"