apiVersion: v1
kind: Service
metadata:
  name: helloworld-service-ilb
  annotations:
    networking.gke.io/load-balancer-type: "Internal"
spec:
  type: LoadBalancer
  externalTrafficPolicy: Cluster
  selector:
    app: hello-server
  ports:
  - name: tcp-port
    protocol: TCP
    port: 8080
    targetPort: 8080